MvcLogicApps/MvcLogicApps/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcLogicApps.Models
{
    public class Doctor
    {
        public string IdDoctor { get; set; }

        public string Apellido { get; set; }

        public string Especialidad { get; set; }

        public int Salario { get; set; }

        public string Hospital { get; set; }
    }
}

MvcLogicApps/MvcLogicApps/Models/EmailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcLogicApps.Models
{
    public class EmailModel
    {
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
    }
}

MvcLogicApps/MvcLogicApps/Models/ErrorViewModel.cs
using System;

namespace MvcLogicApps.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcLogicApps/MvcLogicApps/Models/Tabla.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcLogicApps.Models
{
    public class Tabla
    {
        public int Resultado { get; set; }
    }
}

MvcLogicApps/MvcLogicApps/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcLogicApps.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcLogicApps.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcLogicApps/MvcLogicApps/Controllers/LogicAppsController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLogicApps.Models;
using MvcLogicApps.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcLogicApps.Controllers
{
    public class LogicAppsController : Controller
    {
        private ServiceLogicApps service;

        public LogicAppsController(ServiceLogicApps service) {

            this.service = service;
        }

        public IActionResult SendMail()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendMail(EmailModel model) {

            await this.service.SendMail(model.Email, model.Subject, model.Body);

            ViewData["MENSAJE"] = "Logic Apps de Mail en proceso!!";

            return View();
        }

        public IActionResult SumarNumeros() {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SumarNumeros(int numero1, int numero2) {

            string respuesta = await this.service.SumarNumerosAsync(numero1, numero2);

            ViewData["MENSAJE"] = respuesta;

            return View();
        }

        public IActionResult TablaMultiplicar()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> TablaMultiplicar(int numero) {

            List<Tabla> tabla = await this.service.TablaMultiplicarAsync(numero);

            return View(tabla);
        }

        public IActionResult CreateDoctor() {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateDoctor(Doctor doctor) {

            await this.service.InsertarDoctorAsync(doctor);

            ViewData["MENSAJE"] = "Doctor Insertado";

            return View();
        }

        public async Task<IActionResult> Doctores() {

            List<Doctor> doctores = await this.service.GetDoctoresAsync();

            return View(doctores);
        }

        public async Task<IActionResult> DetailsDoctor(string iddoctor) {

            Doctor doctor = await this.service.FindDoctorAsync(iddoctor);

            return View(doctor);
        }

        public IActionResult AnalizarComentario()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AnalizarComentario(string comentario) {

            string respuesta = await this.service.AnalizarComentariosAsync(comentario);

            ViewData["RESPUESTA"] = respuesta;

            return View();
        }
    }
}

MvcLogicApps/MvcLogicApps/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcLogicApps</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcLogicApps</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LogicApps" asp-action="SumarNumeros">Sumar Numeros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LogicApps" asp-action="SendMail">Mail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LogicApps" asp-action="TablaMultiplicar">Tabla Multiplicar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LogicApps" asp-action="CreateDoctor">Crear Doctor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LogicApps" asp-action="Doctores">Doctores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LogicApps" asp-action="AnalizarComentario">Comentario IA</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcLogicApps - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>