MvcAlumnosApiToken/MvcAlumnosApiToken/Models/Alumno.cs
using Microsoft.Azure.Cosmos.Table;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcAlumnosApiToken.Models
{
    public class Alumno:TableEntity
    {
        public string IdAlumno { get; set; }
        public string Curso { get; set; }

        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public int Nota { get; set; }
    }
}

MvcAlumnosApiToken/MvcAlumnosApiToken/Models/ErrorViewModel.cs
using System;

namespace MvcAlumnosApiToken.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcAlumnosApiToken/MvcAlumnosApiToken/Controllers/AlumnosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcAlumnosApiToken.Models;
using MvcAlumnosApiToken.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcAlumnosApiToken.Controllers
{
    public class AlumnosController : Controller
    {
        private ServiceTableAlumno service;

        public AlumnosController(ServiceTableAlumno service) {

            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            string token = HttpContext.Session.GetString("TOKEN");

            if (token == null)
            {

                ViewData["MENSAJE"] = "Debe generar un TOKEN";
            }
            else {

                List<Alumno> alumnos = await this.service.GetAlumnosAsync(token);
                return View(alumnos);
            }

            return View();
        }
    }
}

MvcAlumnosApiToken/MvcAlumnosApiToken/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcAlumnosApiToken.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcAlumnosApiToken.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcAlumnosApiToken/MvcAlumnosApiToken/Controllers/TokenController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcAlumnosApiToken.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcAlumnosApiToken.Controllers
{
    public class TokenController : Controller
    {
        private ServiceApiToken service;

        public TokenController(ServiceApiToken service) {

            this.service = service;
        }

        public IActionResult GenerarToken()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GenerarToken(string curso) {

            string token = await this.service.GetTokenAsync(curso);

            //ALMACENAMOS EN SESSION EL TOKEN GENERADO
            HttpContext.Session.SetString("TOKEN", token);
            ViewData["TOKEN"] = token;

            return View();
        }
    }
}

MvcAlumnosApiToken/MvcAlumnosApiToken/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcAlumnosApiToken</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcAlumnosApiToken</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Token" asp-action="GenerarToken">Generar Token</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alumnos" asp-action="Index">Cargar Alumnos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcAlumnosApiToken - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcAlumnosApiToken/MvcAlumnosApiToken/Views/Token/GenerarToken.cshtml
<h1 style="color:blue">Generar SAS Token Alumnos</h1>

<form method="post">
    <label>Introduzca curso:</label>
    <input type="text" name="curso" class="form-control" />
    <button type="submit" class="btn btn-danger">Generar Token</button>
</form>

<h2 style="color:red">
    @ViewData["TOKEN"]
</h2>